Resources:
  LB8A12904C:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      LoadBalancerAttributes: []
      Scheme: internal
      Subnets:
        - Fn::Select:
            - 0
            - Fn::Split:
                - ","
                - Fn::ImportValue: VPC:TheVPCPrivateSubnetIDsE53B48B1
      Type: network
    Metadata:
      aws:cdk:path: NLB/LB/Resource
  LBapi1listenerAAC7334B:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: LBapi1listenerService1Group08CC0D1B
          Type: forward
      LoadBalancerArn:
        Ref: LB8A12904C
      Port: 2000
      Protocol: TCP
    Metadata:
      aws:cdk:path: NLB/LB/api1_listener/Resource
  LBapi1listenerService1Group08CC0D1B:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: TCP
      TargetGroupAttributes: []
      Targets: []
      TargetType: instance
      VpcId:
        Fn::ImportValue: VPC:TheVPCVpcIdD346CDBA
    Metadata:
      aws:cdk:path: NLB/LB/api1_listener/Service-1Group/Resource
  LBapi2listener9434057D:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: LBapi2listenerService2Group1BFE736D
          Type: forward
      LoadBalancerArn:
        Ref: LB8A12904C
      Port: 3000
      Protocol: TCP
    Metadata:
      aws:cdk:path: NLB/LB/api2_listener/Resource
  LBapi2listenerService2Group1BFE736D:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: TCP
      TargetGroupAttributes: []
      Targets: []
      TargetType: instance
      VpcId:
        Fn::ImportValue: VPC:TheVPCVpcIdD346CDBA
    Metadata:
      aws:cdk:path: NLB/LB/api2_listener/Service-2Group/Resource
  LBapi3listenerC7F2EA36:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - TargetGroupArn:
            Ref: LBapi3listenerService3Group5B371CC3
          Type: forward
      LoadBalancerArn:
        Ref: LB8A12904C
      Port: 4000
      Protocol: TCP
    Metadata:
      aws:cdk:path: NLB/LB/api3_listener/Resource
  LBapi3listenerService3Group5B371CC3:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: TCP
      TargetGroupAttributes: []
      Targets: []
      TargetType: instance
      VpcId:
        Fn::ImportValue: VPC:TheVPCVpcIdD346CDBA
    Metadata:
      aws:cdk:path: NLB/LB/api3_listener/Service-3Group/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=0.29.0,@aws-cdk/assets=0.29.0,@aws-cdk/aws-apigateway=0.29.0,@aws-cdk/aws-autoscaling=0.29.0,@aws-cdk/aws-autoscaling-common=0.29.0,@aws-cdk/aws-cloudwatch=0.29.0,@aws-cdk/aws-codedeploy-api=0.29.0,@aws-cdk/aws-ec2=0.29.0,@aws-cdk/aws-elasticloadbalancingv2=0.29.0,@aws-cdk/aws-events=0.29.0,@aws-cdk/aws-iam=0.29.0,@aws-cdk/aws-kms=0.29.0,@aws-cdk/aws-lambda=0.29.0,@aws-cdk/aws-s3=0.29.0,@aws-cdk/aws-s3-notifications=0.29.0,@aws-cdk/aws-sqs=0.29.0,@aws-cdk/cdk=0.29.0,@aws-cdk/cx-api=0.29.0,@aws-cdk/region-info=0.29.0,jsii-runtime=node.js/v11.2.0
Outputs:
  LBLoadBalancerArn4723B1BD:
    Value:
      Ref: LB8A12904C
    Export:
      Name: NLB:LBLoadBalancerArn4723B1BD
  ExportsOutputRefLBapi1listenerService1Group08CC0D1B06253457:
    Value:
      Ref: LBapi1listenerService1Group08CC0D1B
    Export:
      Name: NLB:ExportsOutputRefLBapi1listenerService1Group08CC0D1B06253457
  ExportsOutputRefLBapi2listenerService2Group1BFE736D62692502:
    Value:
      Ref: LBapi2listenerService2Group1BFE736D
    Export:
      Name: NLB:ExportsOutputRefLBapi2listenerService2Group1BFE736D62692502
  ExportsOutputRefLBapi3listenerService3Group5B371CC32ADF98B4:
    Value:
      Ref: LBapi3listenerService3Group5B371CC3
    Export:
      Name: NLB:ExportsOutputRefLBapi3listenerService3Group5B371CC32ADF98B4
